### ISSUE TITLE
Message d'erreur pour outil Bluenove

### ISSUE THREAD

**Issue by ArnauddeChampsavin** [consultation-gouv/deploiement.consultation#20]
Quand le formulaire de l'outi BlueNove est envoyé :

- Prévenir ETALAB de la tentative (ex: mail auto) 
- Prévenir l'utilisateur que sa demande est en cours de traitement (ex: mail auto), que l'équipe d'ETALAB va le revenir vers lui avec l'accès à la plateforme, et fournir le mail de contact si besoin.

**Comment by consultationgouv** [comment]
La mécanique est en place : le message d'erreur des backends CapCo et BlueNove est masqué lors de la confirmation, et l'utilisateur est invité à envoyer un mail à consultation@etalab.gouv.fr.

L'envoi de mail automatique chaque nuit fournira dans tous les cas à etalab@ les informations entrées par la personne demandant la consultation.

Ces changements ne sont pas encore en prod, mais pour l'instant uniquement en pprod.

**Comment by sdelafond** [comment]
Pour référence, les pages de pprod concernées : 

https://deploiement.pprod.consultation.etalab.gouv.fr/outil/cap-collectif
https://deploiement.pprod.consultation.etalab.gouv.fr/outil/assembl

**Comment by consultationgouv** [comment]
Disponible en prod.
